version: '3'
services:

  webapp:
    image: node
    build: .
    container_name: webapp
    command: yarn develop
    # mount the host directories and files
    # volumes within the container
    # this means that:
    #  Any change that the developer applies to files on the host
    #  machine immediately takes effect within the container (no docker
    #  rebuild required).
    volumes:
      - ./content:/app/content
      - ./src:/app/src
      - ./static:/app/static
      - ./gatsby-config.js:/app/gatsby-config.js
    # we can see the server running at "localhost:8000"
    ports:
      - "8000:8000"
    # This is supposed to be here to restart the server if it goes down
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  cypress:
    image: cypress
    build: ./test
    container_name: cypress
    depends_on:
      - webapp
    # note: inside cypress container, the network allows accessing
    # "webapp" host under name "webapp"
    # so "curl http://webapp" would return whatever the webserver
    # in the "webapp" container is cooking
    # see https://docs.docker.com/compose/networking/
    environment:
      - CYPRESS_baseUrl=http://webapp:8000
    command: bash -c "(npx wait-on http://webapp:8000 ; rm -r cypress/report cypress/screenshots cypress/videos ; npx cypress run --browser ${BROWSER:-electron} --headless ; npx mochawesome-merge cypress/report/.jsons/*.json > cypress/report/mochawesome.json ; ( cd cypress/report ; npx marge mochawesome.json ))"
    # mount the host directory cypress and the file cypress.json as
    # volumes within the container
    # this means that:
    #  1. Anything that Cypress writes to these folders (e.g., screenshots,
    #     videos) appears also on the Docker host's filesystem
    #  2. Any change that the developer applies to Cypress files on the host
    #     machine immediately takes effect within the e2e container (no docker
    #     rebuild required).
    volumes:
      - ./test/cypress:/app/cypress
      - ./test/cypress.json:/app/cypress.json
